---
- name: Install, configure and start Apache
  host: Apache
  become: true
  task:
  - name: Install epel repo CentOS
    yum: name=epel-release state=present
    when: ansible_distribution == "CentOS"

  - name: Install Apache CentOS
    yum: pkg=httpd state=latest
    when: ansible_distribution == "CentOS"
    
  - name: Start Apache CentOS
    service: name=httpd state=started
    when: ansible_distribution == "CentOS"
    
  - name: Install Apache Ubuntu
    apt: name=apache2 state=latest
    when: ansible_distribution == "Ubuntu"
    
  - name: Install PHP
    apt: name=libapache2-mod-php state=latest
    when: ansible_distribution == "Ubuntu"
