---
- hosts: Apache
  become: true
  tasks:
    - name: Install epel repo CentOS
      yum: name=epel-release state=present
      when: ansible_distribution == "CentOS"

    - name: Install Apache CentOS
      yum: pkg=httpd state=latest
      when: ansible_distribution == "CentOS"
      
    - name: Start Apache CentOS
      service: name=httpd state=started
      when: ansible_distribution == "CentOS"
      
    - name: Install Apache Ubuntu
      apt: 
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"
