---                               
- name: Create New Users
  gather_facts: false
  hosts: centos
  tasks:
    - name: Create Users Task
      user:
        name: ansible
        state: present
        password: "Colonial1"
        shell: /bin/bash
        groups: wheel
        append: true
