---                               
- name: Create New Users
  hosts: ubuntu
  gather_facts: false
  become: yes
  tasks:
    - name: Create Users Task
      user:
        name: ansible
        state: present
        password: "Colonial1"
        shell: /bin/bash
        groups: sudo
        append: true
